name: End to end tests
on:
 push:
   paths-ignore:
     - 'README.md'
   branches:
     - main
 pull_request:
   paths-ignore:
     - 'README.md'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       include:
         - label: "local-encryption"
         - label: "remote-auto"
         - label: "remote-static"
         - label: "remote-https-pinned"
         - label: "remote-https-bad-cert"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: |
          ./earthly.sh +e2e-tests --LABEL=${{ matrix.label }}
